### ISSUE TITLE
Can kubefire be deployed in DigitalOcean or Linode?

### ISSUE THREAD

**Issue by hisk** [innobead/kubefire#72]
I'm interested in using Kubefire and I'm wondering if it's supported in DigitalOcean. Additionally, would it be possible to provide me with installation instructions for setting up Kubefire on DigitalOcean?

Thank you for your help!

**Comment by innobead** [comment]
You can run `kubefire info` to see if the environment is supported or not, but basically you need to see if virtualization works on DO. (I assume it's DO droplet, so nested virtualization probably works)
